#!/bin/bash

#BSUB -J "ae_texture_dev"
#BSUB -q dev
#BSUB -n 1
#BSUB -R "rusage[ngpus_excl_p=1] span[hosts=1]"
#BSUB -e "../results/derr/%J.stderr"
#BSUB -o "../results/dout/%J.stdout"
module load Anaconda3/2019.03-rhel-7
cd ../scripts
python3 run.py -l 'texture' -e 100 -s 32 -b 16 -lr 0.001

: << ////
python3 run.py -l 'mse_spectral' -e 80 -s 32 -b 16 -lr 0.0001
python3 run.py -l 'mse_spectral' -e 150 -s 32 -b 16 -lr 0.0001
python3 run.py -l 'mse_spectral' -e 300 -s 32 -b 16 -lr 0.0001
python3 run.py -l 'mse_spectral' -e 500 -s 32 -b 16 -lr 0.0001
////
